const BYTE = 1024;

export const MAX_IMAGE_SIZE = 15;
export const MAX_IMAGE_SIZE_IN_BYTES = MAX_IMAGE_SIZE * BYTE * BYTE;
export const MAX_IMAGE_SIZE_FORMATTED = MAX_IMAGE_SIZE_IN_BYTES / BYTE / BYTE;

export const MAX_VIDEO_SIZE = 2;
export const MAX_VIDEO_SIZE_IN_BYTES = MAX_VIDEO_SIZE * BYTE * BYTE * BYTE;
export const MAX_VIDEO_SIZE_FORMATTED =
  MAX_VIDEO_SIZE_IN_BYTES / BYTE / BYTE / BYTE;
